/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-12-05 10:43:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.shouye;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class shouye1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<style>\r\n");
      out.write("\t*{\r\n");
      out.write("\t\tmargin: 0;\r\n");
      out.write("\t\tpadding: 0;\r\n");
      out.write("\t\tbox-sizing: border-box;\r\n");
      out.write("\t}\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\tmin-width: 320px;\r\n");
      out.write("\t\tmax-width: 540px;\r\n");
      out.write("\t\t/*background-color:antiquewhite;*/\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t\theight: 1000;\r\n");
      out.write("\t\tfont: 400 16px/1.5 PingFangSC-regular,Tahoma,\"Lucida Grande\",Verdana,\"Microsoft Yahei\",STXihei,hei;\r\n");
      out.write("\t\tbackground-image:url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/image/bj1.jpg);\r\n");
      out.write("\t\tbackground-size：contain；\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\theader{\r\n");
      out.write("\t\theight:83.5px;\r\n");
      out.write("\t}\r\n");
      out.write("\theader img{\r\n");
      out.write("\t\theight:100%;\r\n");
      out.write("\t\twidth:auto;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\theader p{\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\ttext-shadow: 0 2px 1px rgba(0,0,0,.2);\r\n");
      out.write("\t\tfont: 400 32px/1.5 PingFangSC-regular,Tahoma,\"Lucida Grande\",Verdana,\"Microsoft Yahei\",STXihei,hei;\r\n");
      out.write("\t\tpadding-top:20px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tnav{\r\n");
      out.write("\t\tborder:1px solid #ccc;\r\n");
      out.write("\t\tpadding: 4px;\r\n");
      out.write("\t}\r\n");
      out.write("\tnav a{\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\tcolor:#fff;\r\n");
      out.write("\t\ttext-shadow: 0 2px 1px rgba(0,0,0,.2);\r\n");
      out.write("\t}\r\n");
      out.write("\t.row{\r\n");
      out.write("\t\theight:90px;\r\n");
      out.write("\t\tdisplay:flex;\r\n");
      out.write("\t\tborder-radius: 5px;\r\n");
      out.write("\t\toverflow: hidden;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.row2{\r\n");
      out.write("\t\theight:90px;\r\n");
      out.write("\t\tdisplay:flex;\r\n");
      out.write("\t\tborder-radius: 5px;\r\n");
      out.write("\t\toverflow: hidden;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.row3{\r\n");
      out.write("\t\theight:90px;\r\n");
      out.write("\t\tdisplay:flex;\r\n");
      out.write("\t\tborder-radius: 5px;\r\n");
      out.write("\t\toverflow: hidden;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.row div{\r\n");
      out.write("\t\theight:100%;\r\n");
      out.write("\t\tflex: 1;\r\n");
      out.write("\t\tbackground: #FF697A;\r\n");
      out.write("\t\tborder-right: 1px solid #fff;\r\n");
      out.write("\t}\r\n");
      out.write("\t.row3 div{\r\n");
      out.write("\t\theight:100%;\r\n");
      out.write("\t\tflex: 1;\r\n");
      out.write("\t\tbackground:#3495ff;\r\n");
      out.write("\t\tborder-right: 1px solid #fff;\r\n");
      out.write("\t}\r\n");
      out.write("\t.row2 div{\r\n");
      out.write("\t\theight:100%;\r\n");
      out.write("\t\tflex: 1;\r\n");
      out.write("\t\tbackground:#3caf1d;\r\n");
      out.write("\t\tborder-right: 1px solid #fff;\r\n");
      out.write("\t}\r\n");
      out.write("\t.row33 div:nth-child(3){\r\n");
      out.write("\t\tborder-right:0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.row div a{\r\n");
      out.write("\t\tdisplay:block;\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\theight:100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.row2 div a{\r\n");
      out.write("\t\tdisplay:block;\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\theight:100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.row3 div a{\r\n");
      out.write("\t\tdisplay:block;\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\theight:100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.row a{\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tline-height: 45px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.row2 a{\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tline-height: 45px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.row3 a{\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tline-height: 45px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.row11 a{\r\n");
      out.write("\t\tpadding-top: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.row33{\r\n");
      out.write("\t\tdisplay:flex;\r\n");
      out.write("\t\tflex-direction:column;\r\n");
      out.write("\t}\r\n");
      out.write("\t.row33 a{\r\n");
      out.write("\t\tflex:1;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tline-height: 45px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.row33 a{\r\n");
      out.write("\t\tborder-bottom:1px solid #fff;\r\n");
      out.write("\t}\r\n");
      out.write("\t.second{\r\n");
      out.write("\t\tpadding-top:5px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.thrid{\r\n");
      out.write("\t\tpadding-top:5px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("\t<p>资源服务功能</p>\r\n");
      out.write("\t</header>\r\n");
      out.write("<div class=\"biggest\">\r\n");
      out.write("<nav>\r\n");
      out.write("<!--第一部分-->\r\n");
      out.write("<div class=\"first\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"row11\">\r\n");
      out.write("\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t服务功能\t\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<div class=\"row33\">\r\n");
      out.write("\t\t\t<a href=\"http://localhost:8080/First/searchbook/searchbookindex.jsp\">\r\n");
      out.write("\t\t\t\t图书查阅\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t电子资源\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<div class=\"row33\">\r\n");
      out.write("\t\t\t<a href=\"http://localhost:8080/First/logindwonload/login1.jsp\">\r\n");
      out.write("\t\t\t新生培训\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t学术检索\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<!--第二部分-->\r\n");
      out.write("<div class=\"second\">\r\n");
      out.write("<div class=\"row2\">\r\n");
      out.write("\t\t<div class=\"row11\">\r\n");
      out.write("\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t借阅服务\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<div class=\"row33\">\r\n");
      out.write("\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t借阅规则\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t借阅办理\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<div class=\"row33\">\r\n");
      out.write("\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t阅读推荐\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t馆际互借\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t   </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!--第三部分-->\r\n");
      out.write("<div class=\"thrid\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"row3\">\r\n");
      out.write("\t\t<div class=\"row11\">\r\n");
      out.write("\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t研究支持\t\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<div class=\"row33\">\r\n");
      out.write("\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t学科服务\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t数据服务\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<div class=\"row33\">\r\n");
      out.write("\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t科技查新\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t分析报告\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
