/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-12-15 06:50:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bangshangxinshu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <title>山东师范大学图书管理系统</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/font-awesome.min.css\">                \r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/bootstrap.min333.css\">                                      \r\n");
      out.write("    <!-- Bootstrap style -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/hero-slider-style.css\">                              \r\n");
      out.write("    <!-- Hero slider style (https://codyhouse.co/gem/hero-slider/) -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/magnific-popup.css\">                                 \r\n");
      out.write("    <!-- Magnific popup style (http://dimsemenov.com/plugins/magnific-popup/) -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/tooplate-style.css\">                                   \r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\t<style>\r\n");
      out.write(".roe{\r\n");
      out.write("   padding-top:20px;\r\n");
      out.write("   color: #fff;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("   font-size: 50px;\r\n");
      out.write("   font-family:'STKaiti';\r\n");
      out.write("   background-color:#00008B\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Content -->\r\n");
      out.write("        <div class=\"cd-hero\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Navigation -->        \r\n");
      out.write("            <div class=\"cd-slider-nav\">\r\n");
      out.write("\t\t\t\t<div class=\"roe\">\r\n");
      out.write("        山东师范大学图书管理系统\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("            </div> \r\n");
      out.write("\r\n");
      out.write("            <ul class=\"cd-hero-slider\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Page 1 Gallery One -->\r\n");
      out.write("                <li class=\"selected\">                    \r\n");
      out.write("                    <div class=\"cd-full-width\">\r\n");
      out.write("                        <div class=\"container-fluid js-tm-page-content\" data-page-no=\"1\" data-page-type=\"gallery\">\r\n");
      out.write("                            <div class=\"tm-img-gallery-container\">\r\n");
      out.write("                                <div class=\"tm-img-gallery gallery-one\">\r\n");
      out.write("                                <!-- Gallery One pop up connected with JS code below -->                                    \r\n");
      out.write("                                    <div class=\"tm-img-gallery-info-container\">                                    \r\n");
      out.write("                                        <h2 class=\"tm-text-title tm-gallery-title tm-white\"><span class=\"tm-white\">榜上新书</span></h2>\r\n");
      out.write("                                        <p class=\"tm-text\">以下书籍均为近一周内图书馆新上图书，以便满足同学们的需求。\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"grid-item\">\r\n");
      out.write("                                        <figure class=\"effect-bubba\">\r\n");
      out.write("                                            <img src=\"images/pinang.png\" alt=\"Image\" class=\"img-fluid tm-img\">\r\n");
      out.write("                                            <figcaption>\r\n");
      out.write("                                                <h2 class=\"tm-figure-title\">皮<span>囊</span></h2>\r\n");
      out.write("                                                <p class=\"tm-figure-description\">央视著名主持朱迅自传.</p>\r\n");
      out.write("                                                <a href=\"images/pinang.png\">View more</a>\r\n");
      out.write("                                            </figcaption>           \r\n");
      out.write("                                        </figure>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"grid-item\">\r\n");
      out.write("                                        <figure class=\"effect-bubba\">\r\n");
      out.write("                                            <img src=\"images/cikedewenrou.png\" alt=\"Image\" class=\"img-fluid tm-img\">\r\n");
      out.write("                                            <figcaption>\r\n");
      out.write("                                                <h2 class=\"tm-figure-title\">此刻的温柔</span></h2>\r\n");
      out.write("                                                <p class=\"tm-figure-description\">Be With You.</p>\r\n");
      out.write("                                                <a href=\"images/cikedewenrou.png\">View more</a>\r\n");
      out.write("                                            </figcaption>           \r\n");
      out.write("                                        </figure>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"grid-item\">\r\n");
      out.write("                                        <figure class=\"effect-bubba\">\r\n");
      out.write("                                            <img src=\"images/fushengliuji.png\" alt=\"Image\" class=\"img-fluid tm-img\">\r\n");
      out.write("                                            <figcaption>\r\n");
      out.write("                                                <h2 class=\"tm-figure-title\">浮生六记</span></h2>\r\n");
      out.write("                                                <p class=\"tm-figure-description\">文言文畅销书</p>\r\n");
      out.write("                                                <a href=\"images/fushengliuji.png\">View more</a>\r\n");
      out.write("                                            </figcaption>           \r\n");
      out.write("                                        </figure>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"grid-item\">\r\n");
      out.write("                                        <figure class=\"effect-bubba\">\r\n");
      out.write("                                            <img src=\"images/moqiu.png\" alt=\"Image\" class=\"img-fluid tm-img\">\r\n");
      out.write("                                            <figcaption>\r\n");
      out.write("                                                <h2 class=\"tm-figure-title\">魔<span>球</span></h2>\r\n");
      out.write("                                                <p class=\"tm-figure-description\">东野圭吾佳作.</p>\r\n");
      out.write("                                                <a href=\"images/moqiu.png\">View more</a>\r\n");
      out.write("                                            </figcaption>           \r\n");
      out.write("                                        </figure>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>                                 \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>                                                    \r\n");
      out.write("                    </div>                    \r\n");
      out.write("                </li>       \r\n");
      out.write("        <div id=\"loader-wrapper\">\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"loader\"></div>\r\n");
      out.write("            <div class=\"loader-section section-left\"></div>\r\n");
      out.write("            <div class=\"loader-section section-right\"></div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- load JS files -->\r\n");
      out.write("        <script src=\"js/jquery-1.11.3.min.js\"></script>         <!-- jQuery (https://jquery.com/download/) -->\r\n");
      out.write("        <script src=\"js/tether.min.js\"></script> <!-- Tether for Bootstrap (http://stackoverflow.com/questions/34567939/how-to-fix-the-error-error-bootstrap-tooltips-require-tether-http-github-h) --> \r\n");
      out.write("        <script src=\"js/bootstrap.min333.js\"></script>             <!-- Bootstrap js (v4-alpha.getbootstrap.com/) -->\r\n");
      out.write("        <script src=\"js/hero-slider-main.js\"></script>          <!-- Hero slider (https://codyhouse.co/gem/hero-slider/) -->\r\n");
      out.write("        <script src=\"js/jquery.magnific-popup.min.js\"></script> <!-- Magnific popup (http://dimsemenov.com/plugins/magnific-popup/) -->\r\n");
      out.write("        \r\n");
      out.write("        <script>\r\n");
      out.write("\r\n");
      out.write("            function adjustHeightOfPage(pageNo) {\r\n");
      out.write("\r\n");
      out.write("                var offset = 80;\r\n");
      out.write("                var pageContentHeight = 0;\r\n");
      out.write("\r\n");
      out.write("                var pageType = $('div[data-page-no=\"' + pageNo + '\"]').data(\"page-type\");\r\n");
      out.write("\r\n");
      out.write("                if( pageType != undefined && pageType == \"gallery\") {\r\n");
      out.write("                    pageContentHeight = $(\".cd-hero-slider li:nth-of-type(\" + pageNo + \") .tm-img-gallery-container\").height();\r\n");
      out.write("                }\r\n");
      out.write("                else {\r\n");
      out.write("                    pageContentHeight = $(\".cd-hero-slider li:nth-of-type(\" + pageNo + \") .js-tm-page-content\").height() + 20;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                if($(window).width() >= 992) { offset = 120; }\r\n");
      out.write("                else if($(window).width() < 480) { offset = 40; }\r\n");
      out.write("               \r\n");
      out.write("                // Get the page height\r\n");
      out.write("                var totalPageHeight = $('.cd-slider-nav').height()\r\n");
      out.write("                                        + pageContentHeight + offset\r\n");
      out.write("                                        + $('.tm-footer').height();\r\n");
      out.write("\r\n");
      out.write("                // Adjust layout based on page height and window height\r\n");
      out.write("                if(totalPageHeight > $(window).height()) \r\n");
      out.write("                {\r\n");
      out.write("                    $('.cd-hero-slider').addClass('small-screen');\r\n");
      out.write("                    $('.cd-hero-slider li:nth-of-type(' + pageNo + ')').css(\"min-height\", totalPageHeight + \"px\");\r\n");
      out.write("                }\r\n");
      out.write("                else \r\n");
      out.write("                {\r\n");
      out.write("                    $('.cd-hero-slider').removeClass('small-screen');\r\n");
      out.write("                    $('.cd-hero-slider li:nth-of-type(' + pageNo + ')').css(\"min-height\", \"100%\");\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /*\r\n");
      out.write("                Everything is loaded including images.\r\n");
      out.write("            */\r\n");
      out.write("            $(window).load(function(){\r\n");
      out.write("\r\n");
      out.write("                adjustHeightOfPage(1); // Adjust page height\r\n");
      out.write("\r\n");
      out.write("                /* Gallery One pop up\r\n");
      out.write("                -----------------------------------------*/\r\n");
      out.write("                $('.gallery-one').magnificPopup({\r\n");
      out.write("                    delegate: 'a', // child items selector, by clicking on it popup will open\r\n");
      out.write("                    type: 'image',\r\n");
      out.write("                    gallery:{enabled:true}                \r\n");
      out.write("                });\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t/* Gallery Two pop up\r\n");
      out.write("                -----------------------------------------*/\r\n");
      out.write("\t\t\t\t$('.gallery-two').magnificPopup({\r\n");
      out.write("                    delegate: 'a',\r\n");
      out.write("                    type: 'image',\r\n");
      out.write("                    gallery:{enabled:true}                \r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                /* Gallery Three pop up\r\n");
      out.write("                -----------------------------------------*/\r\n");
      out.write("                $('.gallery-three').magnificPopup({\r\n");
      out.write("                    delegate: 'a',\r\n");
      out.write("                    type: 'image',\r\n");
      out.write("                    gallery:{enabled:true}                \r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                /* Collapse menu after click \r\n");
      out.write("                -----------------------------------------*/\r\n");
      out.write("                $('#tmNavbar a').click(function(){\r\n");
      out.write("                    $('#tmNavbar').collapse('hide');\r\n");
      out.write("\r\n");
      out.write("                    adjustHeightOfPage($(this).data(\"no\")); // Adjust page height       \r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                /* Browser resized \r\n");
      out.write("                -----------------------------------------*/\r\n");
      out.write("                $( window ).resize(function() {\r\n");
      out.write("                    var currentPageNo = $(\".cd-hero-slider li.selected .js-tm-page-content\").data(\"page-no\");\r\n");
      out.write("                    \r\n");
      out.write("                    // wait 3 seconds\r\n");
      out.write("                    setTimeout(function() {\r\n");
      out.write("                        adjustHeightOfPage( currentPageNo );\r\n");
      out.write("                    }, 1000);\r\n");
      out.write("                    \r\n");
      out.write("                });\r\n");
      out.write("        \r\n");
      out.write("                // Remove preloader (https://ihatetomatoes.net/create-custom-preloading-screen/)\r\n");
      out.write("                $('body').addClass('loaded');\r\n");
      out.write("                           \r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("           \r\n");
      out.write("\r\n");
      out.write("        </script>            \r\n");
      out.write("\r\n");
      out.write("</body></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
