/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-12-19 04:50:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Fristpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta content=\"图书管理\" http-equiv=\"keywords\">\r\n");
      out.write("<meta name=\"description\" content=\"图书管理\">\r\n");
      out.write("<meta name=\"applicable-device\" content=\"pc,mobile\">\r\n");
      out.write("<meta http-equiv=\"Cache-Control\" content=\"no-siteapp\"/>\r\n");
      out.write("<meta http-equiv=\"Cache-Control\" content=\"no-transform\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\"> \r\n");
      out.write("<style>\r\n");
      out.write(".roe{\r\n");
      out.write("   padding-top:20px;\r\n");
      out.write("   color: #fff;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("   font-size: 50px;\r\n");
      out.write("   font-family:'STKaiti';\r\n");
      out.write("}\r\n");
      out.write(".roa{\r\n");
      out.write("   text-align:right;\r\n");
      out.write("   float:right ;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<title>图书管理</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/index.css\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.SuperSlide.2.1.1.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/public.js\"></script><!-- 菜单js等-->\r\n");
      out.write("<!-- 时间选择js -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/laydate.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--头部-->\r\n");
      out.write("<div class=\"topbox bg\">\r\n");
      out.write("\t<div class=\"wid_main fix\">\r\n");
      out.write("\t\t<div class=\"logo l\"><img src=\"\"  /></div>\r\n");
      out.write("\t\t<!-- 搜索 -->\r\n");
      out.write("\t\t<div class=\"roe\">\r\n");
      out.write("\t\t山东师范大学图书管理系统\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- top end -->\r\n");
      out.write("\r\n");
      out.write("<!-- 主体内容框 -->\r\n");
      out.write("<div class=\"contentbox wid_main bora_5\">\r\n");
      out.write("\t<div class=\"content\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 导航end -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 需要添加的最新通知或公告滚动部分 -->\r\n");
      out.write("\t\t<div class=\"gonggao bdb_d fix\">\r\n");
      out.write("\t\t\t<div class=\"txtScroll-top l fix\">\r\n");
      out.write("\t\t\t\t<div class=\"l tit\"><img src=\"images/icon_notice.png\"><b class=\"dib vm\">信息速递：</b></div>\r\n");
      out.write("\t\t\t\t<div class=\"bd l\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"infoList\">\r\n");
      out.write("\t\t\t\t\t\t<li>图书馆西二净水器更换，同学们可放心用水！<span class=\"date\">2019-12-11</span></li>\r\n");
      out.write("\t\t\t\t\t\t<li>阳面遮阳布已经部署完成，今天中午投入使用！<span class=\"date\">2019-12-13</span></li>\r\n");
      out.write("\t\t\t\t\t\t<li>关于图书馆惩治不文明占座的征求意见！<span class=\"date\">2019-12-14</span></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\tjQuery(\".txtScroll-top\").slide({titCell:\".hd ul\",mainCell:\".bd ul\",effect:\"topLoop\",autoPlay:true,vis:1,interTime:4000,});\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 时间 -->\r\n");
      out.write("\t\t\t<div class=\"timebox fc r\">\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" src=\"js/show_date.js\"></script>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"conbox fix\">\r\n");
      out.write("\t\t\t<!-- 轮播图 -->\r\n");
      out.write("\t\t\t<div class=\"news_banner l bora_5\">\r\n");
      out.write("                <div class=\"hd\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                    \t<li>1</li>\r\n");
      out.write("                    \t<li>2</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"bd\">\r\n");
      out.write("                    <ul><!--图片新闻 最多4-5个左右li -->\r\n");
      out.write("                    \t<li>\r\n");
      out.write("                            <a href=\"http://localhost:8080/First/haoshutuijian.jsp\"><img src=\"images/haoshu.png\" alt=\"好书推荐\" /></a>\r\n");
      out.write("                            <h2><a href=\"http://localhost:8080/First/haoshutuijian.jsp\">好书推荐</a></h2>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"http://localhost:8080/First/bangshangxinshu.jsp\"><img src=\"images/bangshang.png\" alt=\"榜上新书\" /></a>\r\n");
      out.write("                            <h2><a href=\"http://localhost:8080/First/bangshangxinshu.jsp\">榜上新书</a></h2>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 下面是前/后按钮代码，如果不需要删除即可 -->\r\n");
      out.write("                <a class=\"prev\" href=\"javascript:void(0)\"></a>\r\n");
      out.write("                <a class=\"next\" href=\"javascript:void(0)\"></a>\r\n");
      out.write("\r\n");
      out.write("                <script type=\"text/javascript\">\r\n");
      out.write("                jQuery(\".news_banner\").slide({mainCell:\".bd ul\",autoPlay:true,effect:\"leftLoop\",mouseOverStop:false,interTime:5000,});\r\n");
      out.write("                </script>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 部分主要入口 -->\r\n");
      out.write("            <div class=\"about_enter r\">\r\n");
      out.write("            \t<ul class=\"fix\">\r\n");
      out.write("            \t\t<li><a href=\"http://localhost:8080/First/logindwn/login1.jsp\"><img src=\"images/icon_leader.png\"><span>学生服务</span></a></li>\r\n");
      out.write("            \t\t<li><a href=\"http://localhost:8080/First/jieyueguize.jsp\"><img src=\"images/icon_jigou.png\"><span>借阅规则</span></a></li>\r\n");
      out.write("            \t\t<li><a href=\"http://localhost:8080/First/logindwn/adminlogin.jsp\"><img src=\"images/icon_people.png\"><span>管理员服务</span></a></li>\r\n");
      out.write("            \t\t<li><a href=\"http://localhost:8080/First/duzhepeixun.jsp\"><img src=\"images/icon_order.png\"><span>读者培训</span></a></li>\r\n");
      out.write("            \t</ul>\r\n");
      out.write("            \t<dl>\r\n");
      out.write("            \t\t<dd><a href=\"#\"><img src=\"images/icon_alltel.png\"><span>馆长热线  0531-5203</span></a></dd>\r\n");
      out.write("            \t\t<dd><a><img src=\"images/icon_hottel.png\"><span>读者投诉  0531-5530</span></a></dd>\r\n");
      out.write("            \t\t<dd><a href=\"http://localhost:8080/First/jieshuliucheng.jsp\"><img src=\"images/icon_liucheng.png\"><span>借阅流程</span></a></dd>\r\n");
      out.write("            \t</dl>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
